import { v4 as uuidv4 } from "uuid";

export const foods = [
  {
    id: uuidv4(),
    name: "Meat Pizza",
    img: "sliceline/images/meat-pizza.jpg",
    category: "Pizza",
    price: 20,
  },
  {
    id: uuidv4(),
    name: "Sausage Pizza",
    img: "sliceline/images/sausage-pizza.jpg",
    category: "Pizza",
    price: 20,
  },
  {
    id: uuidv4(),
    name: "Peperoni Pizza",
    img: "sliceline/images/peperoni-pizza.jpg",
    category: "Pizza",
    price: 15,
  },
  {
    id: uuidv4(),
    name: "Meat Burger",
    img: "sliceline/images/meat-burger.jpg",
    category: "Burger",
    price: 12,
  },
  {
    id: uuidv4(),
    name: "Chicken Burger",
    img: "sliceline/images/chicken-burger.jpg",
    category: "Burger",
    price: 17,
  },
  {
    id: uuidv4(),
    name: "Chicken Wings",
    img: "sliceline/images/chicken-wings.jpg",
    category: "Chicken",
    price: 18,
  },
  {
    id: uuidv4(),
    name: "Fried Chicken",
    img: "sliceline/images/fried-chicken.jpg",
    category: "Chicken",
    price: 16,
  },
  {
    id: uuidv4(),
    name: "Pasta",
    img: "sliceline/images/pasta.jpg",
    category: "Pasta",
    price: 21,
  },
  {
    id: uuidv4(),
    name: "Noodles",
    img: "sliceline/images/noodles.jpg",
    category: "Noodles",
    price: 13,
  },
  {
    id: uuidv4(),
    name: "French Fried",
    img: "sliceline/images/french-fried.jpg",
    category: "Appetizers",
    price: 7,
  },
  {
    id: uuidv4(),
    name: "Salad",
    img: "sliceline/images/salad.jpg",
    category: "Appetizers",
    price: 4,
  },
];
